name: tides
channels:
  - conda-forge
dependencies:
  - python=3.11
  - arrow
  - astral<3
  - fastapi
  - matplotlib
  - numpy
  - plotly
  - polars
  - pyarrow
  - pydantic
  - requests
  - scipy
  - uvicorn
  - pip
  - pip:
      - timezonefinder